- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      changed_when: false
    - name: Update all packages to the latest version
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
    - name: Install packages
      apt:
        name: 
          - htop
          - mc
          - tmux