- name: Localhost Play
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
  tasks:
    - name: Include tasks from packages.yml
      ansible.builtin.include_tasks: tasks/packages.yml
    - name: Include tasks from users.yml  
      ansible.builtin.include_tasks: tasks/users.yml
