- name: Localhost Play
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
  tasks:
    - name: Include tasks from packages.yml
      ansible.builtin.include_tasks: tasks/packages.yml
    - name: Include tasks from users.yml
      ansible.builtin.include_tasks: tasks/users.yml
    - name: Include tasks from cron.yml
      ansible.builtin.include_tasks: tasks/cron.yml
    - name: Include tasks from logrotate.yml
      ansible.builtin.include_tasks: tasks/logrotate.yml
    - name: Include tasks from alias.yml
      ansible.builtin.include_tasks: tasks/alias.yml
