- name: Install Cronjob ansible pull
  ansible.builtin.cron:
    user: ansible
    name: "Ansible Pull"
    minute: "*/10"
    job: "ansible-pull -o -U https://github.com/Mongstaen/ansible-pull-tests.git > /dev/null"
